Load_on_start:
  - 'zone1'
Leaderboards:
  enabled: false
  type: mysql
  redis_db_info:
    host: 'localhost'
    port: 6379
  mysql_db_info:
    host: 'localhost'
    name: 'minecraft'
    port: 3306
    user: 'user'
    password: 'password'
Region_Provider_Plugin: WorldGuard
External_Economy_Link:
  enabled: false
  external_to_internal:
    allow: true
    # internal = external * rate
    rate: 1
  internal_to_external:
    allow: false
    # external = internal * rate
    rate: 0.5
Zones:
  zone1:
    max_number_of_players: 10
    world: 'world'
    mob_check_task_interval: 300
    soft_mob_respawn: false
    clear_drops: true
    clear_mob_xp: false
    one_time_use_keys: false
    entrance:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    lobby:
      x: 0
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    starting_money: 35
    kits:
      player:
        - '298-1'
        - '299-1'
        - '300-1'
        - '301-1'
        - '272-1'
        - '297-3'
      donator:
        - '306-1'
        - '307-1'
        - '308-1'
        - '309-1'
        - '267-1|16-2'
        - '364-3'
      admin:
        - '310-1'
        - '311-1'
        - '312-1'
        - '313-1'
        - '276-1|17-5|16-5'
        - '322-3'
    money_rewards:
      - 'Zombie:10-15-5'
      - 'Skeleton:15-20-6'
      - 'Spider:15-18-6'
    sub_zones:
      subzone1:
        number_of_mobs: 10
        mob_types:
          - 'Zombie'
          - 'Spider'
          - 'Skeleton'
      subzone2:
        number_of_mobs: 10
        mob_types:
          - 'Zombie'
          - 'Spider'
      subzone3:
        number_of_mobs: 10
        mob_types:
          - 'Zombie'
          - 'Skeleton'
