name: Quarantine
main: me.DDoS.Quarantine.Quarantine
softdepend: [WorldGuard]
version: 0.5.1
commands:
  qload:
      description: Load the desired zone.
      usage:
          /qload (zone name)
  qunload:
      description: Unload the desired zone.
      usage:
          /qunload (zone name)
  qrespawnmobs:
      description: Respawn the mobs in the desired zone.
      usage:
          /qrespawnmobs (zone name)
  qconvertinv:
      description: Convert the inventories to the new format.
      usage:
          /qconvertinv (zone name)
  qjoin:
      description: Join the desired zone.
      usage:
          /qjoin (zone name)
  qenter:
      description: Enter the desired zone.
      usage:
          /qenter
  qsetlobby:
      description: Set the lobby for the desired zone.
      usage:
          /qsetlobby (zone name)
  qsetentrance:
      description: Set the entrance for the desired zone.
      usage:
          /qsetentrance (zone name)
  qleave:
      description: Leave for the desired zone.
      usage:
          /qleave
  qmoney:
      description: Tells the players there current account balance.
      usage:
          /qmoney
  qkeys:
      description: Tells the players their keys.
      usage:
          /qkeys
  qscore:
      description: Tells the players their score.
      usage:
          /qscore
  qrank:
      description: Tells the players their rank.
      usage:
          /qrank
  qtop:
      description: Tells the players the top five players.
      usage:
          /qtop
  qzones:
      description: Shows the list of zones to the player.
      usage:
          /qzones
  qplayers:
      description: Shows the list of player in a zone.
      usage:
          /qplayers
  qkit:
      description: Gives to a player the requested kit.
      usage:
          /qkit (kit name)
          
permissions:
  quarantine.play: 
    description: play in zones
  quarantine.setup: 
    description: setup the spawn and lobby
  quarantine.admin: 
    description: load and unload the zones
    